{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openshift-dashboard.fullname" . }}-frontend
  labels:
    {{- include "openshift-dashboard.labels" . | nindent 4 }}
    component: frontend
spec:
  ports:
  - port: {{ .Values.services.frontend.port }}
    targetPort: {{ .Values.services.frontend.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "openshift-dashboard.selectorLabels" . | nindent 4 }}
    component: frontend
  type: {{ .Values.services.frontend.type }}
{{- end }}

