apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openshift-dashboard.fullname" . }}-backend-app
  labels:
    {{- include "openshift-dashboard.labels" . | nindent 4 }}
data:
  app.py: |
{{ .Files.Get "files/backend-app.py" | indent 4 }}
