{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openshift-dashboard.fullname" . }}-redis
  labels:
    {{- include "openshift-dashboard.labels" . | nindent 4 }}
    component: redis
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.port }}
    name: redis
  selector:
    {{- include "openshift-dashboard.selectorLabels" . | nindent 4 }}
    component: redis
{{- end }}
