{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openshift-dashboard.fullname" . }}-redis
  labels:
    {{- include "openshift-dashboard.labels" . | nindent 4 }}
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "openshift-dashboard.selectorLabels" . | nindent 6 }}
      component: redis
  template:
    metadata:
      labels:
        {{- include "openshift-dashboard.selectorLabels" . | nindent 8 }}
        component: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.redis.service.port }}
          name: redis
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
{{- end }}
