apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml.template
  - nginx-configmap.yaml
  - frontend-files-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - route.yaml

commonLabels:
  app: openshift-dashboard

